<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:lg="http://www.edustandaard.nl/leerresultaten/1/leerlinggegevens"
  xmlns:aut="http://www.edustandaard.nl/leerresultaten/1/autorisatie"
  targetNamespace="http://www.edustandaard.nl/leerresultaten/1/leerlinggegevens">
  <!-- ================================================================== -->
  <!--* WSDL bestand voor de afspraak Leerresultaten - Leerlinggegevens
    
    SVN: $Id: UWLR_Leerlinggegevens.wsdl 1233 2012-11-12 13:59:30Z erik $
  -->
  <!-- ================================================================== -->
  <!-- Schema definities: -->
  <!-- -->
  <wsdl:types>
    <xs:schema>
      <xs:import schemaLocation="../Schemas/UWLR_Leerlinggegevens_v1p0.xsd"
        namespace="http://www.edustandaard.nl/leerresultaten/1/leerlinggegevens"/>
      <xs:import schemaLocation="../Schemas/UWLR_Autorisatie_v1p0.xsd"
        namespace="http://www.edustandaard.nl/leerresultaten/1/autorisatie"/>
    </xs:schema>
  </wsdl:types>
  <!-- -->
  <!-- ================================================================== -->
  <!-- Berichten -->
  <!-- -->
  <wsdl:message name="msgHeader">
    <wsdl:part name="msgpHeader" element="aut:autorisatie"/>
  </wsdl:message>
  <!-- -->
  <wsdl:message name="msgLeerlinggegevensVerzoek">
    <wsdl:part name="msgpLeerlinggegevensVerzoek" element="lg:leerlinggegevensverzoek"/>
  </wsdl:message>
  <!-- -->
  <wsdl:message name="msgLeerlinggegevensAntwoord">
    <wsdl:part name="msgpLeerlinggegevensAntwoord" element="lg:leerlinggegevensantwoord"/>
  </wsdl:message>
  <!-- -->
  <!-- ================================================================== -->
  <!-- Port: -->
  <!-- -->
  <wsdl:portType name="prtLeerlinggegevens">
    <wsdl:operation name="HaalLeerlinggegevens">
      <wsdl:input message="lg:msgLeerlinggegevensVerzoek"/>
      <wsdl:output message="lg:msgLeerlinggegevensAntwoord"/>
    </wsdl:operation>
  </wsdl:portType>
  <!-- -->
  <!-- ================================================================== -->
  <!-- Binding: -->
  <!-- -->
  <wsdl:binding name="bndLeerlinggegevens" type="lg:prtLeerlinggegevens">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="HaalLeerlinggegevens">
      <soap:operation soapAction="HaalLeerlinggegevens"/>
      <wsdl:input>
        <soap:header message="lg:msgHeader" part="msgpHeader" use="literal"/>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <!-- -->
  <!-- ================================================================== -->
  <!-- Service: -->
  <!-- -->
  <wsdl:service name="LeerlinggegevensService">
    <wsdl:port name="prtLeerlinggegevensService" binding="lg:bndLeerlinggegevens">
      <soap:address location="http://localhost:8080/NOTDEFINEDYET"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
